# Welcome to Jekyll!
title: NSIO Homelab
email:
description: >-
  Ramblings of someone stumbling through problems, and saving notes for myself.
github_username: nathanshannon
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nathan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I like tech"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://nateshannon.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nathanshannon"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nathanshannon"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # categories
  - scope:
      path: "/categories/"
      type: liquid
  # tags
  - scope:
      path: "/tags/"
      type: liquid

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
